title: My first Jekyll Blog
author: Camille Regnault
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog de lordinatrice - Camille Regnault.
  Articles d'une développeuse sur la tech et le développement.
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
